# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@main
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          #  - repo
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: wroyca
          filename: metrics.markdown.full.md
          markdown: >-
            https://raw.githubusercontent.com/lowlighter/metrics/master/source/templates/markdown/example.md
          config_output: markdown
          base: header, activity, community, repositories, metadata
          base_hireable: yes
          base_indepth: yes
          config_octicon: yes
          config_padding: 0, 10 + 8%
          config_timezone: America/New_York
          repositories_skipped: |
            @use.patterns
            marshmallow-project/*
